### ISSUE TITLE
Par2cmdline multi threaded 

### ISSUE THREAD

**Issue by Safihre** [clinton-hall/test#2]
Hi @clinton-hall it's the sabnzbd guy again ;) 
I was wondering:
Do you use regular par2cmdline for your sabnzbd package or some modified version? 
Would it be possible to change this to par2cmdline-mt? 
It's the simple multi threaded version of par2cmdline with very minimal changes: https://github.com/Parchive/par2cmdline/compare/master...jkansanen:master

I have been testing this and especially on lower power devices like a NAS or raspberry pi, these simple changes help a lot. 

Let me know what you think :)

**Comment by clinton-hall** [comment]
I'll try and have a look. Shouldn't be an issue, it's just about time.
I haven't updated or looked at these apps for a while....

**Comment by Safihre** [comment]
It seems it's already in there, I see in the changelog 

> SABnzbdplus build 130128
> - multicore par2 added

Great :)
