### ISSUE TITLE
can not open sabnzbd on server port 8800

### ISSUE THREAD

**Issue by tillyjump** [clinton-hall/test#3]
Hi,

I did see some other posts of people having the same problem:

install Git : succes
install Python 3.5.0.2 : succes
install SABnzbdplus 160522: Fail
install Python 2.7.3 and turn off 3.5.0.2 : succes
Install SABnzbplus 160522: Succes

opening SABnzbplus via App center or home screen: Failed, cannot make connection to server error

i use the Qnap TAS-268

i hope some one can help me, after trying over 6 hours im clueless

**Comment by clinton-hall** [comment]
via ssh

    /etc/init.d/sabnzbd.sh restart

**Comment by alsopeter** [comment]
Hi Clinton-hall,

Have the same problem. 
SABnzbd was working until I did update to QTS 4.2.2
I possibly missed an QTS update
Nu running ts-559 Pro+ with QTS 4.2.2
Intel Atom D525 1.8 GHz dual core processor
Optware IPKG 0.99.163
git 2.1.0 via https://www.dropbox.com/s/fiay536scdscew7/git_2.1.0_x86.qpkg
SABnzbdplus 160522 via https://www.dropbox.com/s/jms3ma8e4c0c1jh/SABnzbdplus_160522.qpkg

Clicking open button of app opens new window, but browser keeps trying to open SABnzb user interface without result.
When dropping nzb in sabnzb/nzb, it won't disappear as it should.
A folder is created in the incomplete folder with the same name as the nzb.
In this folder, folder _ADMIN_ is created, but that is all so something is working.
Without user interface on nasname:8800/sabnzbd/

If I restart sabnzbd, it shows that it is stopping and restarting.
Did i do something wrong?

Regards,
Peter
