### ISSUE TITLE
SABYenc for QNAP package

### ISSUE THREAD

**Issue by Safihre** [clinton-hall/test#4]
Hi @clinton-hall, so many places that your active that I don't even know where to contact you 😉 

We just released 2.0.0Alpha and it will include [a new C-module](https://pypi.python.org/pypi/sabyenc) that gives a very big performance increase to SABnzbd.
It's available via `pip install sabyenc` (already includes pre-compiled packages for x64/x86 platforms).

Just wanted to let you know some time in advance, so by the time the 2.0.0Final comes it can be in the QNAP packages :)

Thank you!

**Comment by clinton-hall** [comment]
Yes, @Safihre 
I have seen.... important job interview comming up. Just trying to do some research/study etc to put best foot forward. Hoping to find some time to look into this after I know where my future lies....

**Comment by Safihre** [comment]
Good luck :)

**Comment by discoltk** [comment]
Sorry to hijack this thread but question is directly related.

I got as far as getting pip installed on QNAP, but it seems the yenc module's binary for ARM isn't on the repo so I need python-dev to build it.   Is there a convenient qpkg for this?   Just trying to find the most expedient way to get this working without building out a whole ARM toolchain or something.

100% of downloads are failing to verify, so it seems to be impacting more than just performance on
SABnzbd Version: 2.0.0-develop  on QNAP

Good luck with the interview =)

EDIT**   I managed to get sabyenc built and working.   The failing to verify was a whole other issue.

**Comment by Safihre** [comment]
So the failing to verify is unrelated? Sure? :p

**Comment by discoltk** [comment]
Not 100% sure, but it was still failing to verify after I got sabyenc working.    There was an issue with one of the data sources that was, I think, the root cause of the failure to verify.    I could break sabyenc I suppose to check for sure ;)

**Comment by Safihre** [comment]
I did just recently found issues with 2.0.0 when Sabyenc wasn't installed, so it's definitely possible to see more failures without Sabyenc.

**Comment by discoltk** [comment]
Well, good to know I'm not going crazy ;)
